### ISSUE TITLE
Python 3.7 SyntaxError

### ISSUE THREAD

**Issue by jayvdb** [ncorbuk/SubZone#13]
Using the version on PyPI
```py
> subzone
Traceback (most recent call last):
  File "/usr/bin/subzone", line 11, in <module>
    load_entry_point('subzone==0.2.8', 'console_scripts', 'subzone')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/subzone/__init__.py", line 6
    from .__version__ import __copyright__, 
                            ^
SyntaxError: trailing comma not allowed without surrounding parentheses
```

**Comment by ncorbuk** [comment]
Hmm, yea I did this code in Python 3.6.5. Will look into this when I get some free time. Thanks. :)
